using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SoccerClub.Models
{
	public class CartItem
	{
		[Key] // Define Id as the primary key
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Configure Id to be generated by the database
		public int Id { get; set; }

		public int ProductId { get; set; }
		public int HeaderId { get; set; }
		public int Quantity { get; set; }
		public Product Product { get; set; }
	}

}
